dev_path: /dev/input/js0
hid_path: /dev/hidraw3
debug: true
use_user_mapping: true

enable_rumble: true

axis_map:
  X Axis: 0
  Y Axis: 1
  Z Axis: 2
  Rx Axis: 3
  Ry Axis: 4
  Rz Axis: 5
  Hat0X: 6
  Hat0Y: 7

button_map:
  A: 0
  B: 1
  X: 2
  Y: 3
  LB: 4
  RB: 5
  Back: 6
  Start: 7
  Guide: 8
  Left Thumb: 9
  Right Thumb: 10

